services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql
      - ./schema:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./exports:/app/exports

volumes:
  db_data:
