use std::collections::HashMap;

use rand::distr::{Distribution, weighted::WeightedIndex};
use rand::rng;
use tracing::{debug, info, warn};

use crate::domain::generation::{GenerationParams, is_sentence_boundary_str, score_generation};
use crate::domain::token::{TextFragment, bos_token, eos_token, tokenize_fragments};
use crate::infrastructure::db::token_repository::TokenRecord;
use crate::state::SharedState;

/// Orchestrates text generation from the stored n-gram statistics.
///
/// Generation is intentionally richer than a plain Markov chain over a single
/// order:
/// - **Backoff**: if the exact high-order continuation is unknown, fall back to
///   lower-order prefixes instead of stopping.
/// - **Diversity**: temperature, top-k and top-p (nucleus) sampling avoid the
///   generic, repetitive continuations that raw frequency weighting produces.
/// - **Natural stopping**: once a minimum length is reached, generation prefers
///   to stop at a sentence boundary rather than mid-word.
pub struct GeneratorService {
    state: SharedState,
}

/// The outcome of a generation run: the plain-text message to send plus any
/// sticker media (file paths or `file_id`s) the model selected mid-chain.
pub struct GeneratedOutput {
    pub text: String,
    pub stickers: Vec<String>,
    /// Number of tokens generated beyond the prefix. Read by the unit tests.
    #[allow(dead_code)]
    pub generated: usize,
}

impl GeneratorService {
    pub fn new(state: SharedState) -> Self {
        Self { state }
    }

    /// Generates text given a prefix. `chat_id` scopes generation to the
    /// messages of that chat; when `None` (no chat context), statistics from
    /// all chats are used.
    pub async fn generate_text_for_prefix(
        &self,
        prefix: String,
        max_tokens: usize,
        chat_id: Option<i64>,
    ) -> anyhow::Result<GeneratedOutput> {
        info!(
            max_tokens,
            ?chat_id,
            prefix_len = prefix.len(),
            "generate_text_for_prefix invoked"
        );

        let max_tokens = max_tokens.max(1).min(self.state.config.max_generation_length);
        let params = self.generation_params();
        let num_candidates = self.state.config.num_candidates.max(1);

        let bos_id = self.state.store.ensure_token(&bos_token()).await?;
        let eos_id = self.state.store.ensure_token(&eos_token()).await?;

        let prefix_tokens = tokenize_fragments(&[TextFragment::Text(prefix)]);

        debug!(token_count = prefix_tokens.len(), "prefix tokenized");

        let bos_padding = self.state.ngram_size.saturating_sub(1).max(1);

        let mut base = Vec::with_capacity(prefix_tokens.len() + bos_padding);
        base.extend(std::iter::repeat_n(bos_id, bos_padding));
        for token in &prefix_tokens {
            let id = self.state.store.ensure_token(token).await?;
            base.push(id);
        }

        let (best_ids, generated) = self
            .best_of_candidates(&base, chat_id, bos_id, eos_id, max_tokens, params, num_candidates)
            .await?;

        let (text, stickers) = self.render_output(&best_ids, bos_id, eos_id).await?;

        info!(generated, final_len = text.len(), sticker_count = stickers.len(), "text generation completed");

        Ok(GeneratedOutput { text, stickers, generated })
    }

    fn generation_params(&self) -> GenerationParams {
        GenerationParams {
            temperature: self.state.config.generation_temperature,
            top_k: self.state.config.generation_top_k,
            top_p: self.state.config.generation_top_p,
            repetition_penalty: self.state.config.repetition_penalty,
            min_stop_tokens: self.state.config.min_generation_tokens,
        }
    }

    /// Samples `num_candidates` continuations from `base` and keeps the one
    /// with the best quality score. Every candidate is generated by extending
    /// the (BOS-padded) prefix, never by replacing it, so the returned chain
    /// always begins with the prefix's first token.
    #[allow(clippy::too_many_arguments)]
    async fn best_of_candidates(
        &self,
        base: &[i64],
        chat_id: Option<i64>,
        bos_id: i64,
        eos_id: i64,
        max_tokens: usize,
        params: GenerationParams,
        num_candidates: usize,
    ) -> anyhow::Result<(Vec<i64>, usize)> {
        let mut best_ids = base.to_vec();
        let mut best_generated = 0usize;
        let mut best_score = f64::NEG_INFINITY;

        for _ in 0..num_candidates {
            let mut cand = base.to_vec();
            let generated = self
                .generate_from_model(&mut cand, chat_id, max_tokens, eos_id, params)
                .await?;

            let text = self.render_output(&cand, bos_id, eos_id).await?.0;
            let is_truncated = generated >= max_tokens;
            let score = score_generation(&text, is_truncated);

            debug!(score, generated, "candidate scored");

            if score > best_score {
                best_score = score;
                best_ids = cand;
                best_generated = generated;
            }
        }

        Ok((best_ids, best_generated))
    }

    async fn render_output(
        &self,
        token_ids: &[i64],
        bos_id: i64,
        eos_id: i64,
    ) -> anyhow::Result<(String, Vec<String>)> {
        debug!(token_count = token_ids.len(), "render_output called");

        let records = self.state.store.fetch_tokens(token_ids).await?;

        let by_id: HashMap<i64, TokenRecord> = records.into_iter().map(|r| (r.id, r)).collect();

        let mut text = String::new();
        let mut stickers = Vec::new();

        for id in token_ids {
            if *id == bos_id {
                continue;
            }
            if *id == eos_id {
                break;
            }

            let Some(token) = by_id.get(id) else {
                warn!(token_id = id, "missing token record during rendering");
                continue;
            };

            match token.token_type.as_str() {
                "Word" => {
                    if let Some(value) = &token.token_value {
                        text.push_str(value);
                    }
                }
                "Whitespace" => text.push_str(token.token_value.as_deref().unwrap_or(" ")),
                "Newline" => text.push('\n'),
                "Punctuation" => text.push_str(token.token_value.as_deref().unwrap_or("")),
                "CustomEmoji" => {
                    if let Some(value) = token.token_value.as_deref() {
                        text.push_str(value);
                    } else if let Some(emoji_id) = token.emoji_id {
                        text.push_str(&format!("<emoji:{}>", emoji_id));
                    } else {
                        warn!("custom emoji token missing both value and emoji_id");
                        text.push_str("[emoji]");
                    }
                }
                "Sticker" => {
                    if let Some(path) = token.token_value.as_deref() {
                        stickers.push(path.to_string());
                    } else {
                        warn!("sticker token missing its file path");
                    }
                }
                "Special" => {} // skip BOS/EOS when rendering user-facing text
                other => {
                    warn!(token_type = other, "unknown token type during rendering");
                }
            }
        }

        debug!(output_len = text.len(), sticker_count = stickers.len(), "render_output completed");
        Ok((text, stickers))
    }

    /// Runs the autoregressive loop: backoff search over n-gram orders, then a
    /// temperature/top-k/top-p sample, stopping early at a sentence boundary.
    async fn generate_from_model(
        &self,
        token_ids: &mut Vec<i64>,
        chat_id: Option<i64>,
        max_tokens: usize,
        eos_id: i64,
        params: GenerationParams,
    ) -> anyhow::Result<usize> {
        let mut generated = 0usize;

        for step in 0..max_tokens {
            let Some(next_token) = self.sample_next(token_ids, chat_id, params).await? else {
                debug!(step, "no continuation found at any n-gram order");
                break;
            };

            debug!(step, next_token, "sampled next token");

            token_ids.push(next_token);
            generated += 1;

            if next_token == eos_id {
                debug!(step, "EOS reached, stopping generation");
                break;
            }

            if generated >= params.min_stop_tokens && self.is_boundary_token(next_token).await? {
                debug!(step, "stopped at sentence boundary");
                break;
            }
        }

        info!(generated, "generation completed");
        Ok(generated)
    }

    /// Searches n-gram orders from highest to lowest and returns the sampled
    /// continuation for the first order that has any observed candidates.
    ///
    /// When a chat is given, that chat's statistics are preferred; if the chat
    /// has no continuation for a prefix, it falls back to the global
    /// statistics (all chats). With no chat context, only global statistics
    /// are consulted.
    ///
    /// If no higher-order continuation exists, generation falls back to
    /// order-1 (unigram), so it can start with a single token or none at all
    /// regardless of NGRAM_SIZE / MIN_NGRAM_SIZE.
    async fn sample_next(
        &self,
        token_ids: &[i64],
        chat_id: Option<i64>,
        params: GenerationParams,
    ) -> anyhow::Result<Option<i64>> {
        let max_order = self.state.ngram_size.min(token_ids.len() + 1);
        let seen = token_counts(token_ids);

        for order in (self.state.min_ngram_size..=max_order).rev() {
            let prefix_len = order - 1;
            if prefix_len > token_ids.len() {
                continue;
            }
            let start = token_ids.len() - prefix_len;
            let prefix = &token_ids[start..];

            debug!(order, prefix = ?prefix, ?chat_id, "querying n-gram statistics");

            let candidates = self.query_candidates(chat_id, order, prefix).await?;
            if candidates.is_empty() {
                debug!(order, prefix = ?prefix, "no matches at this order, backing off");
                continue;
            }

            let next = sample_from_candidates(&candidates, &seen, &params)?;
            return Ok(Some(next));
        }

        // Order-1 (unigram) fallback: lets generation start with a single token
        // or none at all. When min_ngram_size is already 1, the loop above
        // covers this order.
        if self.state.min_ngram_size > 1 {
            let candidates = self.query_candidates(chat_id, 1, &[]).await?;
            if !candidates.is_empty() {
                debug!("no higher-order continuation; falling back to unigram");
                let next = sample_from_candidates(&candidates, &seen, &params)?;
                return Ok(Some(next));
            }
        }

        Ok(None)
    }

    /// Queries candidates for a prefix, preferring `chat_id`'s statistics and
    /// falling back to the global (all-chat) statistics when the chat has none.
    async fn query_candidates(
        &self,
        chat_id: Option<i64>,
        order: usize,
        prefix: &[i64],
    ) -> anyhow::Result<Vec<(i64, i64)>> {
        let mut candidates = self
            .state
            .store
            .query_next_candidates(chat_id, order, prefix)
            .await?;
        if chat_id.is_some() && candidates.is_empty() {
            debug!(order, "no per-chat continuation, falling back to global statistics");
            candidates = self
                .state
                .store
                .query_next_candidates(None, order, prefix)
                .await?;
        }
        Ok(candidates)
    }

    /// Whether the given token is a natural end-of-sentence marker.
    async fn is_boundary_token(&self, token_id: i64) -> anyhow::Result<bool> {
        Ok(match self.state.store.fetch_token(token_id).await? {
            Some(record) => {
                is_sentence_boundary_str(&record.token_type, record.token_value.as_deref())
            }
            None => false,
        })
    }
}

/// Counts token occurrences in a sequence, used to apply the repetition
/// penalty during sampling.
fn token_counts(ids: &[i64]) -> HashMap<i64, u32> {
    let mut counts = HashMap::new();
    for id in ids {
        *counts.entry(*id).or_insert(0) += 1;
    }
    counts
}

/// Temperature / top-k / top-p / repetition-penalty sampling over n-gram
/// candidates. `seen` is the count of each token already in the generated
/// sequence; candidates that repeat it are down-weighted to break loops.
fn sample_from_candidates(
    candidates: &[(i64, i64)],
    seen: &HashMap<i64, u32>,
    params: &GenerationParams,
) -> anyhow::Result<i64> {
    let temp = params.temperature.max(0.0);

    // Temperature: shape the distribution away from pure frequency weighting.
    let mut weighted: Vec<(usize, f64)> = candidates
        .iter()
        .enumerate()
        .map(|(i, (_, count))| {
            let weight = if temp <= 0.0 {
                *count as f64
            } else {
                (*count as f64).powf(1.0 / temp as f64)
            };
            (i, weight)
        })
        .collect();

    // Repetition penalty: down-weight candidates already used in the sequence.
    if params.repetition_penalty > 1.0 {
        let penalty = params.repetition_penalty as f64;
        for (i, w) in weighted.iter_mut() {
            if let Some(&cnt) = seen.get(&candidates[*i].0) {
                *w *= penalty.powf(-(cnt as f64));
            }
        }
    }

    // Top-k: keep only the k most likely continuations.
    if params.top_k > 0 {
        weighted.sort_by(|a, b| b.1.total_cmp(&a.1));
        weighted.truncate(params.top_k);
    }

    // Top-p (nucleus): keep the smallest set whose cumulative mass >= top_p.
    if params.top_p < 1.0 {
        weighted.sort_by(|a, b| b.1.total_cmp(&a.1));
        let total: f64 = weighted.iter().map(|(_, w)| w).sum();
        if total > 0.0 {
            let mut cum = 0.0;
            let mut keep = 0usize;
            for (_, w) in weighted.iter() {
                cum += w / total;
                keep += 1;
                if cum >= params.top_p as f64 {
                    break;
                }
            }
            weighted.truncate(keep.max(1));
        }
    }

    let best = weighted
        .iter()
        .max_by(|a, b| a.1.total_cmp(&b.1))
        .map(|(i, _)| *i)
        .ok_or_else(|| anyhow::anyhow!("no candidates to sample from"))?;

    // temperature <= 0 means fully greedy.
    if temp <= 0.0 {
        return Ok(candidates[best].0);
    }

    let weights: Vec<f64> = weighted.iter().map(|(_, w)| *w).collect();
    let dist = WeightedIndex::new(weights)
        .map_err(|e| anyhow::anyhow!("invalid n-gram weights: {e}"))?;

    let mut rng = rng();
    let chosen = dist.sample(&mut rng);
    Ok(candidates[weighted[chosen].0].0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::application::trainer::train_text;
    use crate::config::Config;
    use crate::domain::generation::GenerationParams;
    use crate::domain::token::{Token, TokenKind};
    use crate::infrastructure::store::{InMemoryStore, Store};
    use crate::state::AppState;
    use std::sync::Arc;
    use std::time::Duration;

    fn params() -> GenerationParams {
        GenerationParams::default()
    }

    fn no_seen() -> HashMap<i64, u32> {
        HashMap::new()
    }

    /// Minimal config tuned for deterministic, single-candidate generation.
    fn test_config() -> Config {
        Config {
            database_url: String::new(),
            exports_dir: "exports".into(),
            ngram_size: 2,
            min_ngram_size: 2,
            max_generation_length: 64,
            generation_temperature: 0.0, // greedy
            generation_top_k: 0,
            generation_top_p: 1.0,
            repetition_penalty: 1.0,
            num_candidates: 1,
            min_generation_tokens: 1,
            reply_chance: 0.0,
            always_reply_to_username: String::new(),
            sticker_chance: 0.0,
            ingestion_interval: Duration::from_secs(3600),
            ingestion_workers: 1,
            heartbeat_interval: Duration::from_secs(3600),
            bot_token: None,
            use_inmemory_store: true,
            use_hybrid_mode: false,
        }
    }

    #[tokio::test]
    async fn unconinuable_prefix_output_starts_with_first_prefix_token() {
        // Train a continuation that exists only from BOS. The prefix "Привет"
        // has no observed continuation, so the OLD code fell back to a fresh
        // BOS chain and emitted text starting with "мир" — a different token.
        // The fix must keep the chain anchored to the prefix's first token.
        let store = Store::InMemory(InMemoryStore::new());
        let bos_id = store.ensure_token(&bos_token()).await.unwrap();
        let world_id = store
            .ensure_token(&Token::new(TokenKind::Word, Some("мир".into())))
            .await
            .unwrap();
        store.upsert_ngram(7, 2, &[bos_id], world_id).await.unwrap();

        let state = Arc::new(AppState::new(test_config(), Arc::new(store)));
        let svc = GeneratorService::new(state);

        let output = svc
            .generate_text_for_prefix("Привет".into(), 64, None)
            .await
            .unwrap();
        let (text, generated) = (output.text, output.generated);
        assert_eq!(generated, 0);
        assert!(
            text.trim_start().starts_with("Привет"),
            "output must start with the prefix's first token, got: {text:?}"
        );
    }

    #[tokio::test]
    async fn generation_prefers_chat_stats_and_falls_back_to_global() {
        // chat 7 knows [Привет] -> [мир]; the global store also knows a
        // continuation for [Привет] that belongs to another chat. Generating
        // for chat 7 must follow chat 7's own continuation.
        let store = Store::InMemory(InMemoryStore::new());
        store.ensure_token(&bos_token()).await.unwrap();
        let privet = Token::new(TokenKind::Word, Some("Привет".into()));
        let privet_id = store.ensure_token(&privet).await.unwrap();
        let world = Token::new(TokenKind::Word, Some("мир".into()));
        let world_id = store.ensure_token(&world).await.unwrap();
        let other = Token::new(TokenKind::Word, Some("другой".into()));
        let other_id = store.ensure_token(&other).await.unwrap();

        // chat 7: [Привет] -> [мир]
        store.upsert_ngram(7, 2, &[privet_id], world_id).await.unwrap();
        // another chat: [Привет] -> [другой]
        store.upsert_ngram(99, 2, &[privet_id], other_id).await.unwrap();

        let state = Arc::new(AppState::new(test_config(), Arc::new(store)));
        let svc = GeneratorService::new(state);

        // BOS-padded base is [bos, Привет]; at order 2 the prefix is [Привет].
        let output = svc
            .generate_text_for_prefix("Привет".into(), 64, Some(7))
            .await
            .unwrap();
        let (text, generated) = (output.text, output.generated);
        assert_eq!(generated, 1);
        assert!(
            text.contains("мир"),
            "chat-scoped generation must use the chat's own continuation, got: {text:?}"
        );
    }

    #[tokio::test]
    async fn generation_without_chat_uses_global_stats() {
        let store = Store::InMemory(InMemoryStore::new());
        store.ensure_token(&bos_token()).await.unwrap();
        let privet = Token::new(TokenKind::Word, Some("Привет".into()));
        let privet_id = store.ensure_token(&privet).await.unwrap();
        let world = Token::new(TokenKind::Word, Some("мир".into()));
        let world_id = store.ensure_token(&world).await.unwrap();
        store.upsert_ngram(7, 2, &[privet_id], world_id).await.unwrap();

        let state = Arc::new(AppState::new(test_config(), Arc::new(store)));
        let svc = GeneratorService::new(state);

        // No chat context -> falls back to global statistics across all chats.
        let output = svc
            .generate_text_for_prefix("Привет".into(), 64, None)
            .await
            .unwrap();
        let (text, generated) = (output.text, output.generated);
        assert_eq!(generated, 1);
        assert!(
            text.contains("мир"),
            "no-chat generation must use global statistics, got: {text:?}"
        );
    }

    #[tokio::test]
    async fn generation_can_start_from_zero_tokens_via_unigram() {
        // Only unigram (order-1) data exists for chat 7 — no higher-order
        // continuation. Generation must still start from an empty prefix by
        // falling back to the unigram statistics.
        let store = Store::InMemory(InMemoryStore::new());
        store.ensure_token(&bos_token()).await.unwrap();
        let hello_id = store
            .ensure_token(&Token::new(TokenKind::Word, Some("привет".into())))
            .await
            .unwrap();
        store.upsert_ngram(7, 1, &[], hello_id).await.unwrap();

        let state = Arc::new(AppState::new(test_config(), Arc::new(store)));
        let svc = GeneratorService::new(state);

        let output = svc
            .generate_text_for_prefix(String::new(), 64, Some(7))
            .await
            .unwrap();
        let (text, generated) = (output.text, output.generated);
        assert!(generated >= 1, "must generate from unigram fallback");
        assert!(text.contains("привет"));
    }

    #[tokio::test]
    async fn training_enables_generation_from_zero_tokens() {
        // Training a message keeps unigram counts, which lets the model start
        // a random message from an empty prefix.
        let store = Store::InMemory(InMemoryStore::new());
        train_text(&store, 7, "привет мир", 2, 2).await.unwrap();

        let state = Arc::new(AppState::new(test_config(), Arc::new(store)));
        let svc = GeneratorService::new(state);

        let output = svc
            .generate_text_for_prefix(String::new(), 64, Some(7))
            .await
            .unwrap();
        let (text, generated) = (output.text, output.generated);
        assert!(generated >= 1);
        assert!(!text.trim().is_empty());
    }

    #[test]
    fn greedy_picks_highest_count() {
        let candidates = [(1, 5), (2, 50), (3, 1)];
        let mut p = params();
        p.temperature = 0.0;
        for _ in 0..50 {
            assert_eq!(sample_from_candidates(&candidates, &no_seen(), &p).unwrap(), 2);
        }
    }

    #[test]
    fn greedy_ignores_top_k_when_one_dominant() {
        let candidates = [(1, 5), (2, 50), (3, 1)];
        let mut p = params();
        p.temperature = 0.0;
        p.top_k = 1;
        for _ in 0..50 {
            assert_eq!(sample_from_candidates(&candidates, &no_seen(), &p).unwrap(), 2);
        }
    }

    #[test]
    fn greedy_respects_top_p() {
        // With temperature 0 the largest-count candidate always wins, but the
        // nucleus cutoff must still resolve to a valid candidate.
        let candidates = [(1, 1), (2, 1), (3, 100)];
        let mut p = params();
        p.temperature = 0.0;
        p.top_p = 0.5;
        for _ in 0..50 {
            assert_eq!(sample_from_candidates(&candidates, &no_seen(), &p).unwrap(), 3);
        }
    }

    #[test]
    fn empty_candidates_are_an_error() {
        assert!(sample_from_candidates(&[], &no_seen(), &params()).is_err());
    }

    #[test]
    fn repetition_penalty_discourages_reusing_seen_token_in_greedy() {
        // Token 1 has the highest count but is already heavily used; the
        // penalty must push a greedy sample towards the unused token 2.
        let candidates = [(1, 100), (2, 10)];
        let mut p = params();
        p.temperature = 0.0;
        p.repetition_penalty = 4.0;

        let mut seen = HashMap::new();
        seen.insert(1, 5); // 1 already appeared 5 times
        for _ in 0..50 {
            assert_eq!(sample_from_candidates(&candidates, &seen, &p).unwrap(), 2);
        }

        // Without repetition, token 1 would be chosen greedily.
        for _ in 0..50 {
            assert_eq!(sample_from_candidates(&candidates, &no_seen(), &p).unwrap(), 1);
        }
    }

    #[test]
    fn token_counts_aggregate_occurrences() {
        let counts = token_counts(&[7, 7, 9, 7, 10]);
        assert_eq!(counts.get(&7), Some(&3));
        assert_eq!(counts.get(&9), Some(&1));
        assert_eq!(counts.get(&10), Some(&1));
    }
}